export const GithubActionTypes = {
  SEARCH_USERS: 'SEARCH_USERS',
  CLEAR_USERS: 'CLEAR_USERS',
  GET_USER_PROFILE: 'GET_USER_PROFILE',
  GET_USER_REPO: 'GET_USER_REPO',
  SET_LOADING: 'SET_LOADING',
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
};
